version: '3'
services:
  simple_blog_cms_db:
    image: postgres
  simple_blog_cms:
    build: .
    ports:
    - "3000:3000"
    volumes:
    - .:/usr/src/app
    env_file: .env
    stdin_open: true
    tty: true
    depends_on:
      - simple_blog_cms_db
