version: '3'
services:
  pgsql:
    build: .
    ports:
      - "3000:3000"
      volumes:
        - .:/usr/src/app
        env_file: .env
        stdin_open: true
        tty: true
  simple_blog_cms:
    build: .
    ports:
    - "3000:3000"
    volumes:
    - .:/usr/src/app
    env_file: .env
    stdin_open: true
    tty: true
    depends_on:
      - pgsql
