default: &default
  adapter: postgresql
  encoding: unicode
  host: simple_blog_cms_db
  username: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: postgres_development
  password: postgres_development

test:
  <<: *default
  database: postgres_test
  password: postgres_test

production:
  <<: *default
  database: postgres_production
  password: postgres_production
