# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 73bce87ec056085464e2e24207d1716c783dc26875b8c2f07118515dfbb8706b90064aad774cf9886653aefad7bd7ddf48583e349f907323c5a33a14bceb7819

test:
  secret_key_base: e9fedf797001ba522e9236d701ecf8cbdeba0db256372c3b4c6d6140faff544f3a03054de3b9eda52ef4278f8c17b105cb1e22ae86745301be0ac0d4e8b18b17

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
